# Docker安装Server

services:
  xiaozhi-esp32-server:
    build: .
    container_name: xiaozhi-esp32-server
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Asia/Shanghai
    ports:
      # ws服务端
      - "8000:8000"
    volumes:
      # 配置文件目录
      - ./:/app/
